name: Publish

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-cargo:
    runs-on: [self-hosted, debian-default-x86]

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Publish
        run: cargo publish --no-verify --registry whs31 || echo "Already published, skipping"

  publish-conan:
    runs-on: [self-hosted, debian-default-x86]

    steps:
      - uses: actions/checkout@v4

      - name: Create
        run: conan create . -b missing --user quasar --channel dev

      - name: Upload
        run: conan upload "quasar.protobufs/*" -r whs31 --force -c
